local_as: 8
routers:
  - name: lill
    ssh_ip: 158.8.10.1
    router_id: 8.151.0.1
    interfaces:
      - name: ext_7_LILL
        ip: 179.7.8.8/24
        desc: "Link to AS7"
      - name: ixp_82
        ip: 180.82.0.8/24
        desc: "IXP 82"
      - name: host
        ip: 8.101.0.1/24
      - name: lo
        ip: 8.151.0.1/32
      - name: port_STRA
        ip: 8.0.1.1/24
      - name: port_BRES
        ip: 8.0.2.1/24
    ospf_interfaces:
      - 8.101.0.0/24
      - 8.0.2.0/24
      - 8.0.1.0/24
      - 8.151.0.1/32
    ebgp_neighbors:
      - neighbor_ip: 179.7.8.7
        remote_as: 7
        desc: "eBGP to AS7"
        import_rm: IN-PEER
        export_rm: OUT-PEER
      - neighbor_ip: 180.82.0.82
        remote_as: 82
        desc: "eBGP to IXP 82"
        import_rm: IN-PEER
        export_rm: OUT-IXP
    ibgp_neighbors:
      - 8.152.0.1
      - 8.153.0.1
      - 8.154.0.1
      - 8.155.0.1
      - 8.156.0.1
    networks:
      - 8.0.0.0/8
    prefix_lists:
      - name: AS8-AGG
        entries:
          - action: "permit"
            prefix: "8.0.0.0/8"
    community_lists:
      - name: 1
        entries:
          - action: "permit"
            community: "8:100"
      - name: 2
        entries:
          - action: "permit"
            community: "8:200"
      - name: 3
        entries:
          - action: "permit"
            community: "8:300"
    route_maps:
      - name: OUT-PEER
        entries:
          - seq: 10
            action: permit
            match:
              - ip address prefix-list AS23-AGG
          - seq: 20
            action: permit
            match:
              - community 1
      - name: OUT-IXP
        entries:
          - seq: 10
            action: permit
            match:
              - ip address prefix-list AS23-AGG
            set:
              - community 82:2 82:4 82:6 82:8 82:10
          - seq: 20
            action: permit
            match:
              - community 1
            set:
              - community 82:2 82:4 82:6 82:8 82:10
      - name: IN-PEER
        entries:
          - seq: 10
            action: permit
            set:
              - community 23:200
              - local-preference 100

  - name: stra
    ssh_ip: 158.8.11.1
    router_id: 8.152.0.1
    interfaces:
      - name: ext_5_MARS
        ip: 179.5.8.8/24
        desc: "eBGP to AS5"
      - name: host
        ip: 8.102.0.1/24
      - name: lo
        ip: 8.152.0.1/32
      - name: port_LILL
        ip: 8.0.1.2/24
      - name: port_BRES
        ip: 8.0.3.1/24
      - name: port_PARI
        ip: 8.0.4.1/24
      - name: port_MARS
        ip: 8.0.5.1/24
    ospf_interfaces:
      - 8.102.0.0/24
      - 8.0.1.0/24
      - 8.0.3.0/24
      - 8.0.4.0/24
      - 8.0.5.0/24
      - 8.152.0.1/32
    ebgp_neighbors:
      - neighbor_ip: 179.5.8.5
        remote_as: 5
        desc: "eBGP to AS5"
        import_rm: IN-PROV
        export_rm: OUT-PROV
    ibgp_neighbors:
      - 8.151.0.1
    networks:
      - 8.0.0.0/8
    prefix_lists:
      - name: AS8-AGG
        entries:
          - action: "permit"
            prefix: "8.0.0.0/8"
    community_lists:
      - name: 1
        entries:
          - action: "permit"
            community: "8:100"
      - name: 2
        entries:
          - action: "permit"
            community: "8:200"
      - name: 3
        entries:
          - action: "permit"
            community: "8:300"
    route_maps:
      - name: OUT-PROV
        entries:
          - seq: 10
            action: permit
            match:
              - ip address prefix-list AS23-AGG
          - seq: 20
            action: permit
            match:
              - community 1
      - name: IN-PROV
        entries:
          - seq: 10
            action: permit
            set:
              - community 23:300
              - local-preference 50

  - name: bres
    ssh_ip: 158.8.14.1
    router_id: 8.155.0.1
    interfaces:
      - name: ext_6_MARS
        ip: 179.6.8.8/24
        desc: "eBGP to AS6"
      - name: host
        ip: 8.105.0.1/24
      - name: lo
        ip: 8.155.0.1/32
      - name: port_LILL
        ip: 8.0.2.2/24
      - name: port_STRA
        ip: 8.0.3.2/24
      - name: port_TOUL
        ip: 8.0.9.2/24
      - name: port_PARI
        ip: 8.0.10.1/24
    ospf_interfaces:
      - 8.105.0.0/24
      - 8.0.1.0/24
      - 8.0.3.0/24
      - 8.0.9.0/24
      - 8.0.10.0/24
      - 8.155.0.1/32
    ebgp_neighbors:
      - neighbor_ip: 179.6.8.6
        remote_as: 6
        desc: "eBGP to AS6"
        import_rm: IN-PROV
        export_rm: OUT-PROV
    ibgp_neighbors:
      - 8.151.0.1
    networks:
      - 8.0.0.0/8
    prefix_lists:
      - name: AS8-AGG
        entries:
          - action: "permit"
            prefix: "8.0.0.0/8"
    community_lists:
      - name: 1
        entries:
          - action: "permit"
            community: "8:100"
      - name: 2
        entries:
          - action: "permit"
            community: "8:200"
      - name: 3
        entries:
          - action: "permit"
            community: "8:300"
    route_maps:
      - name: OUT-PROV
        entries:
          - seq: 10
            action: permit
            match:
              - ip address prefix-list AS23-AGG
          - seq: 20
            action: permit
            match:
              - community 1
      - name: IN-PROV
        entries:
          - seq: 10
            action: permit
            set:
              - community 23:300
              - local-preference 50

  - name: toul
    ssh_ip: 158.8.13.1
    router_id: 8.154.0.1
    interfaces:
      - name: ext_9_PARI
        ip: 179.8.9.8/24
        desc: "eBGP to AS9"
      - name: host
        ip: 8.104.0.1/24
      - name: lo
        ip: 8.154.0.1/32
      - name: port_MARS
        ip: 8.0.7.2/24
      - name: port_PARI
        ip: 8.0.8.1/24
      - name: port_BRES
        ip: 8.0.9.1/24
    ospf_interfaces:
      - 8.104.0.0/24
      - 8.0.7.0/24
      - 8.0.8.0/24
      - 8.0.9.0/24
      - 8.154.0.1/32
    ebgp_neighbors:
      - neighbor_ip: 179.8.9.9
        remote_as: 9
        desc: "eBGP to AS9"
        import_rm: IN-CUST
        export_rm: OUT-PROV
    ibgp_neighbors:
      - 8.151.0.1
    networks:
      - 8.0.0.0/8
    prefix_lists:
      - name: AS8-AGG
        entries:
          - action: "permit"
            prefix: "8.0.0.0/8"
    community_lists:
      - name: 1
        entries:
          - action: "permit"
            community: "8:100"
      - name: 2
        entries:
          - action: "permit"
            community: "8:200"
      - name: 3
        entries:
          - action: "permit"
            community: "8:300"
    route_maps:
      - name: OUT-CUST
        entries:
          - seq: 10
            action: permit
            match:
              - ip address prefix-list AS23-AGG
          - seq: 20
            action: permit
            match:
              - community 2
      - name: IN-CUST
        entries:
          - seq: 10
            action: permit
            set:
              - community 23:100
              - local-preference 200

  - name: mars
    ssh_ip: 158.8.12.1
    router_id: 8.153.0.1
    interfaces:
      - name: ext_10_PARI
        ip: 179.8.10.8/24
        desc: "eBGP to AS10"
      - name: host
        ip: 8.103.0.1/24
      - name: lo
        ip: 8.153.0.1/32
      - name: port_STRA
        ip: 8.0.5.2/24
      - name: port_PARI
        ip: 8.0.6.1/24
      - name: port_TOUL
        ip: 8.0.7.1/24
    ospf_interfaces:
      - 8.103.0.0/24
      - 8.0.5.0/24
      - 8.0.6.0/24
      - 8.0.7.0/24
      - 8.153.0.1/32
    ebgp_neighbors:
      - neighbor_ip: 179.8.10.10
        remote_as: 10
        desc: "eBGP to AS10"
        import_rm: IN-CUST
        export_rm: OUT-CUST
    ibgp_neighbors:
      - 8.151.0.1
    networks:
      - 8.0.0.0/8
    prefix_lists:
      - name: AS8-AGG
        entries:
          - action: "permit"
            prefix: "8.0.0.0/8"
    community_lists:
      - name: 1
        entries:
          - action: "permit"
            community: "8:100"
      - name: 2
        entries:
          - action: "permit"
            community: "8:200"
      - name: 3
        entries:
          - action: "permit"
            community: "8:300"
    route_maps:
      - name: OUT-CUST
        entries:
          - seq: 10
            action: permit
            match:
              - ip address prefix-list AS23-AGG
          - seq: 20
            action: permit
            match:
              - community 2
      - name: IN-CUST
        entries:
          - seq: 10
            action: permit
            set:
              - community 23:100
              - local-preference 200

  - name: pari
    ssh_ip: 158.8.15.1
    router_id: 8.156.0.1
    interfaces:
      - name: host
        ip: 8.106.0.1/24
      - name: lo
        ip: 8.156.0.1/32
      - name: port_STRA
        ip: 8.0.4.2/24
      - name: port_MARS
        ip: 8.0.6.1/24
      - name: port_BRES
        ip: 8.0.10.1/24
      - name: port_TOUL
        ip: 8.0.8.1/24
    ospf_interfaces:
      - 8.106.0.0/24
      - 8.0.7.0/24
      - 8.0.8.0/24
      - 8.0.9.0/24
      - 8.156.0.1/32
    ibgp_neighbors:
      - 8.151.0.1
    networks:
      - 8.0.0.0/8